apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openshift-external-dns-key
spec:
  data:
  - remoteRef:
      key: coe-lab/isar/infra-external-dns
      property: openshift-external-dns-key
    secretKey: tgis_key
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: openshift-external-dns-key
