apiVersion: v1
kind: Namespace

metadata:
  labels:
    kubernetes.io/metadata.name: openshift-nmstate
    name: openshift-nmstate
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  name: openshift-nmstate
spec:
  finalizers:
  - kubernetes
