apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: coe-netapp-nas
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Filesystem
