apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocp-coe-cert
spec:
  data:
  - remoteRef:
      key: coe-lab/disco/ingress-certificate
      property: cert-chain.crt
    secretKey: tls.crt
  - remoteRef:
      key: coe-lab/disco/ingress-certificate
      property: cert-key.pem
    secretKey: tls.key
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ocp-coe-cert
    template:
      type: kubernetes.io/tls
