apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec:
  mastersSchedulable: false
