apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
spec:
  routeAdmission:
    wildcardPolicy: WildcardsAllowed
  # defaultCertificate:
  #   name: ocp-coe-cert
  replicas: 3
  endpointPublishingStrategy:
    type: HostNetwork
  nodePlacement:
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
