---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-local-storage-vzztn
  namespace: openshift-local-storage
spec:
  targetNamespaces:
    - openshift-local-storage
