apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coe-infra-rdp-service
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      type: static-nfs-2e4c62a0f0
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: coe-infra-rdp-service