apiVersion: v1
kind: PersistentVolume
metadata:
  name: coe-infra-rdp-service
  labels:
    type: static-nfs-2e4c62a0f0
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Gi
  nfs:
    path: /coe_infra_rdp_service
    server: 10.32.97.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem