apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-rdp-service

resources:
  - coe-infra-rdp-service.pv.yaml
  - coe-infra-rdp-service.pvc.yaml
  - VirtualMachine/windows-rdp.yaml
  - Service/windows-rdp.yaml

