apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret
spec:
  data:
  - remoteRef:
      key: coe-lab/isar/rbohne-hcp/pull-secret
      property: .dockerconfigjson
    secretKey: .dockerconfigjson
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pull-secret
    # template:
      # type: kubernetes.io/dockerconfigjson
