apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-key
spec:
  data:
  - remoteRef:
      key: coe-lab/isar/rbohne-hcp/ssh-key
      property: id_rsa
    secretKey: id_rsa
  - remoteRef:
      key: coe-lab/isar/rbohne-hcp/ssh-key
      property: id_rsa.pub
    secretKey: id_rsa.pub
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ssh-key
    # template:
    #   type: kubernetes.io/tls
