apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.cluster.coe.muc.redhat.com
      servingCertificate:
        name: ocp-coe-cert
