apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec:
  templates:
    error:
        name: errors-template
    login:
        name: login-template
    providerSelection:
        name: providers-template
  identityProviders:
  - google:
      clientID: 1079812798374-5boqg26urlclfrp0cqvsoj3ans6cua6f.apps.googleusercontent.com
      clientSecret:
        # google-client-secret-r2qbc
        name: google-client-secret
      hostedDomain: redhat.com
    mappingMethod: claim
    name: RedHatSSO
    type: Google
