apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: coe-bridge-via-enp4s0f1
spec:
  desiredState:
    interfaces:
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp4s0f1
      description: Linux Brige info COE Network via enp4s0f1
      ipv4:
        dhcp: false
        enabled: true
      name: coe-bridge
      state: up
      type: linux-bridge
  nodeSelector:
    coe.muc.redhat.com/second-nic: enp4s0f1