apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec: 
  projectRequestTemplate:
    name: project-request
