apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: coe-cluster-admins
users:
  - astolzen@redhat.com
  - dmoessne@redhat.com
  - rbohne@redhat.com
  - jvonthad@redhat.com
  # Software Endgineer, help to debug hypershift pvc/pv problem
  - lguoqing@redhat.com
  - ocohen@redhat.com
  - fsadeghi@redhat.com
  - dvossel@redhat.com
  - ellorent@redhat.com