apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-client-secret
  namespace: openshift-config
spec:
  data:
  - remoteRef:
      key: coe-lab/isar/redhat-sso
      property: clientSecret
    secretKey: clientSecret
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: google-client-secret
    template:
      engineVersion: v2
      templateFrom:
      - literal: 'argocd.argoproj.io/compare-options: IgnoreExtraneous'
        target: Annotations
