apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-configuration
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://api.rhacm.stormshift.coe.muc.redhat.com:6443
  - namespace: '*'
    server: https://api.ocp4.stormshift.coe.muc.redhat.com:6443
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/stormshift/clusters.git
status: {}
