apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: coe
  namespace: ansible-automation-platform
spec:
  replicas: 1
  postgres_storage_class: coe-netapp-nas
  projects_storage_class: coe-netapp-nas
