kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: stormshift-rhv
  namespace: openshift-mtv
spec:
  data:
  - secretKey: cacert
    remoteRef:
      key: coe-lab/isar/stormshift-rhv
      property: cacert
  - secretKey: insecureSkipVerify
    remoteRef:
      key: coe-lab/isar/stormshift-rhv
      property: insecureSkipVerify
  - secretKey: password
    remoteRef:
      key: coe-lab/isar/stormshift-rhv
      property: password
  - secretKey: url
    remoteRef:
      key: coe-lab/isar/stormshift-rhv
      property: url
  - secretKey: user
    remoteRef:
      key: coe-lab/isar/stormshift-rhv
      property: user
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: stormshift-rhv
    template:
      engineVersion: v2
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
