kind: Secret
apiVersion: v1
metadata:
  name: config-bundle-secret
  namespace: quay-enterprise
type: Opaque
stringData:
  config.yaml: |
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
    AUTHENTICATION_TYPE: Database
    DEFAULT_TAG_EXPIRATION: 2w
    FEATURE_BUILD_SUPPORT: false
    FEATURE_DIRECT_LOGIN: true
    FEATURE_MAILING: false
# New V3.11 features enabled:
    FEATURE_UI_V2: true
    FEATURE_UI_V2_REPO_SETTINGS: true
    FEATURE_AUTO_PRUNE: true
    ROBOTS_DISALLOW: false

    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Red Hat Quay
    SETUP_COMPLETE: true
    TEAM_RESYNC_STALE_TIME: 60m
    TESTING: false
    SUPER_USERS:
      - admin
      - quayadmin
      - rbohne
      - dfroehli
