apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: coe-lab
  namespace: metallb-system
spec:
  ipAddressPoolSelectors:
    - matchExpressions:
        - key: net
          operator: In
          values:
            - coe-lab
