kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
data:
  config.yaml: |
   alertmanagerMain:
     volumeClaimTemplate:
       spec:
         resources:
           requests:
             storage: 10Gi
         storageClassName: ocs-storagecluster-ceph-rbd
   enableUserWorkload: true
   prometheusK8s:
     volumeClaimTemplate:
       spec:
         resources:
           requests:
             storage: 80Gi
         storageClassName: ocs-storagecluster-ceph-rbd
#
