---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/sealed-secrets-operator
  - ../../components/alertreceiver

resources:
  - ../common/

  # Alert manager
  - alertmanager-github-token.yaml
  - alertmanager-main-secret.yaml

  # Custom logo
  - console-custom-logo.configmap.yaml
  - console-operator-config.yaml