apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-nmstate-
  name: openshift-nmstate
  namespace: openshift-nmstate
spec:
  targetNamespaces:
  - openshift-nmstate