apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-client-secret
  namespace: openshift-config
spec:
  data:
  - remoteRef:
      key: coe-lab/coe-cluster/redhat-sso
      property: clientSecret
    secretKey: clientSecret
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: google-client-secret